//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.33440
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MonthlyCycleApp.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class AppResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal AppResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("MonthlyCycleApp.Resources.AppResources", typeof(AppResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 1Luna is a menstrual and fertility app for women. It features a calendar mode.2Luna is a menstrual and fertility app for women. It features a calendar mode.3Luna is a menstrual and fertility app for women. It features a calendar mode.4Luna is a menstrual and fertility app for women. It features a calendar mode.5Luna is a menstrual and fertility app for women. It features a calendar mode.6Luna is a menstrual and fertility app for women. It features a calendar mode.7Luna is a menstrual and fertility app for w [rest of string was truncated]&quot;;.
        /// </summary>
        public static string AboutContent1 {
            get {
                return ResourceManager.GetString("AboutContent1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 8Luna is a menstrual and fertility app for women. It features a calendar mode.Luna is a menstrual and fertility app for women. It features a calendar mode.9Luna is a menstrual and fertility app for women. It features a calendar mode.10Luna is a menstrual and fertility app for women. It features a calendar mode.11Luna is a menstrual and fertility app for women. It features a calendar mode.12Luna is a menstrual and fertility app for women. It features a calendar mode.13Luna is a menstrual and fertility app fo [rest of string was truncated]&quot;;.
        /// </summary>
        public static string AboutContent2 {
            get {
                return ResourceManager.GetString("AboutContent2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 15Luna is a menstrual and fertility app for women. It features a calendar mode.16Luna is a menstrual and fertility app for women. It features a calendar mode.17Luna is a menstrual and fertility app for women. It features a calendar mode.18Luna is a menstrual and fertility app for women. It features a calendar mode.19Luna is a menstrual and fertility app for women. It features a calendar mode.20Luna is a menstrual and fertility app for women. It features a calendar mode.21Luna is a menstrual and fertility ap [rest of string was truncated]&quot;;.
        /// </summary>
        public static string AboutContent3 {
            get {
                return ResourceManager.GetString("AboutContent3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 22Luna is a menstrual and fertility app for women. It features a calendar mode.23Luna is a menstrual and fertility app for women. It features a calendar mode.24Luna is a menstrual and fertility app for women. It features a calendar mode.25Luna is a menstrual and fertility app for women. It features a calendar mode.26Luna is a menstrual and fertility app for women. It features a calendar mode.27Luna is a menstrual and fertility app for women. It features a calendar mode.28Luna is a menstrual and fertility ap [rest of string was truncated]&quot;;.
        /// </summary>
        public static string AboutContent4 {
            get {
                return ResourceManager.GetString("AboutContent4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to About.
        /// </summary>
        public static string AboutHeader {
            get {
                return ResourceManager.GetString("AboutHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Advanced.
        /// </summary>
        public static string Advanced {
            get {
                return ResourceManager.GetString("Advanced", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /InitialSetupPage.xaml.
        /// </summary>
        public static string ApplicationInitialUri {
            get {
                return ResourceManager.GetString("ApplicationInitialUri", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to luna.
        /// </summary>
        public static string ApplicationTitle {
            get {
                return ResourceManager.GetString("ApplicationTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Luna says your {0} medical check is approaching..
        /// </summary>
        public static string BreastControlReminderContent {
            get {
                return ResourceManager.GetString("BreastControlReminderContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Breast control reminder.
        /// </summary>
        public static string BreastControlReminderName {
            get {
                return ResourceManager.GetString("BreastControlReminderName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to calendar.
        /// </summary>
        public static string CalendarPageTitle {
            get {
                return ResourceManager.GetString("CalendarPageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        public static string CancelButton {
            get {
                return ResourceManager.GetString("CancelButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Change.
        /// </summary>
        public static string ChangeButtonText {
            get {
                return ResourceManager.GetString("ChangeButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirm pin.
        /// </summary>
        public static string ConfirmPinText {
            get {
                return ResourceManager.GetString("ConfirmPinText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cycles can range anywhere from 21 to 35 days in adults and from 21 to 45 days in young teens..
        /// </summary>
        public static string CycleDurationSettingExplanation {
            get {
                return ResourceManager.GetString("CycleDurationSettingExplanation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to How long is your cycle?.
        /// </summary>
        public static string CycleDurationSettingText {
            get {
                return ResourceManager.GetString("CycleDurationSettingText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to days until end of period.
        /// </summary>
        public static string DayOfPeriodText {
            get {
                return ResourceManager.GetString("DayOfPeriodText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to days to period.
        /// </summary>
        public static string DaysToPeriodText {
            get {
                return ResourceManager.GetString("DaysToPeriodText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Did it end on.
        /// </summary>
        public static string DelayedPeriodEndQuestion {
            get {
                return ResourceManager.GetString("DelayedPeriodEndQuestion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This means your period is late..
        /// </summary>
        public static string DelayPeriodMessage {
            get {
                return ResourceManager.GetString("DelayPeriodMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do you want to delay tracking?.
        /// </summary>
        public static string DelayPeriodQuestion {
            get {
                return ResourceManager.GetString("DelayPeriodQuestion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The end of cycle you selected is before the confirmed start of cycle. Please pick another date..
        /// </summary>
        public static string EndDateBeforeStartValidation {
            get {
                return ResourceManager.GetString("EndDateBeforeStartValidation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This means your cycle lasted more than twice the average. Is this correct?.
        /// </summary>
        public static string EndDateFarInFutureValidation {
            get {
                return ResourceManager.GetString("EndDateFarInFutureValidation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This means your cycle lasted less than 2 days. Is this correct?.
        /// </summary>
        public static string EndDateTooCloseToStartValidation {
            get {
                return ResourceManager.GetString("EndDateTooCloseToStartValidation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter pin.
        /// </summary>
        public static string EnterPinText {
            get {
                return ResourceManager.GetString("EnterPinText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Based on a 12 months average. Improves prediction based on input..
        /// </summary>
        public static string FertilityForecastExplanationAdvanced {
            get {
                return ResourceManager.GetString("FertilityForecastExplanationAdvanced", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Based on your initial settings. Preffered option when on contraceptive pill..
        /// </summary>
        public static string FertilityForecastExplanationStandard {
            get {
                return ResourceManager.GetString("FertilityForecastExplanationStandard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fertility forecast.
        /// </summary>
        public static string FertilityForecastSetting {
            get {
                return ResourceManager.GetString("FertilityForecastSetting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Luna says your {0} medical check is approaching..
        /// </summary>
        public static string GyneControlReminderContent {
            get {
                return ResourceManager.GetString("GyneControlReminderContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gyne control reminder.
        /// </summary>
        public static string GyneControlReminderName {
            get {
                return ResourceManager.GetString("GyneControlReminderName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to home.
        /// </summary>
        public static string HomePageTitle {
            get {
                return ResourceManager.GetString("HomePageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to When did your last cycle start?.
        /// </summary>
        public static string LastPeriodStartedSetting {
            get {
                return ResourceManager.GetString("LastPeriodStartedSetting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Menstruation reminder.
        /// </summary>
        public static string MenstruationAllarmText {
            get {
                return ResourceManager.GetString("MenstruationAllarmText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Luna estimates your mestruation will begin tomorrow..
        /// </summary>
        public static string MenstruationReminderContent {
            get {
                return ResourceManager.GetString("MenstruationReminderContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Menstruation reminder.
        /// </summary>
        public static string MenstruationReminderName {
            get {
                return ResourceManager.GetString("MenstruationReminderName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Monthly.
        /// </summary>
        public static string Monthly {
            get {
                return ResourceManager.GetString("Monthly", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New pin.
        /// </summary>
        public static string NewPinText {
            get {
                return ResourceManager.GetString("NewPinText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Off.
        /// </summary>
        public static string Off {
            get {
                return ResourceManager.GetString("Off", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ok.
        /// </summary>
        public static string OkButton {
            get {
                return ResourceManager.GetString("OkButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Old pin.
        /// </summary>
        public static string OldPinText {
            get {
                return ResourceManager.GetString("OldPinText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to On.
        /// </summary>
        public static string On {
            get {
                return ResourceManager.GetString("On", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to One time.
        /// </summary>
        public static string OneTime {
            get {
                return ResourceManager.GetString("OneTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This start date is overlapping another existing cycle period. Do you want to modify existing period?.
        /// </summary>
        public static string OverlapExistingPeriodValidation {
            get {
                return ResourceManager.GetString("OverlapExistingPeriodValidation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ovulation reminder.
        /// </summary>
        public static string OvulationAllarmText {
            get {
                return ResourceManager.GetString("OvulationAllarmText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Luna estimates your fertility will be at its peak tomorrow.
        /// </summary>
        public static string OvulationReminderContent {
            get {
                return ResourceManager.GetString("OvulationReminderContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ovulation reminder.
        /// </summary>
        public static string OvulationReminderName {
            get {
                return ResourceManager.GetString("OvulationReminderName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password protection.
        /// </summary>
        public static string PasswordProtectionText {
            get {
                return ResourceManager.GetString("PasswordProtectionText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Menstrual period (usually from 3 to 5 days)..
        /// </summary>
        public static string PeriodDurationSettingExplanation {
            get {
                return ResourceManager.GetString("PeriodDurationSettingExplanation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to How long is your period?.
        /// </summary>
        public static string PeriodDurationSettingText {
            get {
                return ResourceManager.GetString("PeriodDurationSettingText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You know, it&apos;s earlier with {0} days..
        /// </summary>
        public static string PeriodEarlierMessage {
            get {
                return ResourceManager.GetString("PeriodEarlierMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Did your period end on.
        /// </summary>
        public static string PeriodEndedQuestion {
            get {
                return ResourceManager.GetString("PeriodEndedQuestion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Based on a 12 months average. Improves prediction based on input..
        /// </summary>
        public static string PeriodForecastExplanationAdvanced {
            get {
                return ResourceManager.GetString("PeriodForecastExplanationAdvanced", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Based on your initial settings. Preffered option when on contraceptive pill..
        /// </summary>
        public static string PeriodForecastExplanationStandard {
            get {
                return ResourceManager.GetString("PeriodForecastExplanationStandard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ignore unusually longer cycles.
        /// </summary>
        public static string PeriodForecastIgnoreCycles {
            get {
                return ResourceManager.GetString("PeriodForecastIgnoreCycles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Period forecast.
        /// </summary>
        public static string PeriodForecastSetting {
            get {
                return ResourceManager.GetString("PeriodForecastSetting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You know, it&apos;s later with {0} days..
        /// </summary>
        public static string PeriodLaterMessage {
            get {
                return ResourceManager.GetString("PeriodLaterMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Did your period start on.
        /// </summary>
        public static string PeriodStartedQuestion {
            get {
                return ResourceManager.GetString("PeriodStartedQuestion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Luna says it&apos;s time to take your pill..
        /// </summary>
        public static string PillAlarmContent {
            get {
                return ResourceManager.GetString("PillAlarmContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You will receive a notification to take your contraceptive pill..
        /// </summary>
        public static string PillAlarmExplanation {
            get {
                return ResourceManager.GetString("PillAlarmExplanation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pill Alarm by Luna.
        /// </summary>
        public static string PillAlarmName {
            get {
                return ResourceManager.GetString("PillAlarmName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pill reminder.
        /// </summary>
        public static string PillAllarmText {
            get {
                return ResourceManager.GetString("PillAllarmText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Alarm time.
        /// </summary>
        public static string PillAllarmTimeText {
            get {
                return ResourceManager.GetString("PillAllarmTimeText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The pin must have 4 digits..
        /// </summary>
        public static string PinValidationInvalidSize {
            get {
                return ResourceManager.GetString("PinValidationInvalidSize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The {0} cannot be empty. You must enter the pin..
        /// </summary>
        public static string PinValidationMissing {
            get {
                return ResourceManager.GetString("PinValidationMissing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New pin and Confirm pin does not match..
        /// </summary>
        public static string PinValidationNewPinNotMatch {
            get {
                return ResourceManager.GetString("PinValidationNewPinNotMatch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Old pin you introduced doesn&apos;t match your existing pin..
        /// </summary>
        public static string PinValidationOldPinNotMatch {
            get {
                return ResourceManager.GetString("PinValidationOldPinNotMatch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Replace.
        /// </summary>
        public static string ReplaceButton {
            get {
                return ResourceManager.GetString("ReplaceButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reset pin.
        /// </summary>
        public static string ResetPinButtonText {
            get {
                return ResourceManager.GetString("ResetPinButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LeftToRight.
        /// </summary>
        public static string ResourceFlowDirection {
            get {
                return ResourceManager.GetString("ResourceFlowDirection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to en-US.
        /// </summary>
        public static string ResourceLanguage {
            get {
                return ResourceManager.GetString("ResourceLanguage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Set pin.
        /// </summary>
        public static string SetPinButtonText {
            get {
                return ResourceManager.GetString("SetPinButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Settings.
        /// </summary>
        public static string SettingsPageTitle {
            get {
                return ResourceManager.GetString("SettingsPageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Next.
        /// </summary>
        public static string SetupCompletedBtnText {
            get {
                return ResourceManager.GetString("SetupCompletedBtnText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Next.
        /// </summary>
        public static string SetupIncompletedBtnText {
            get {
                return ResourceManager.GetString("SetupIncompletedBtnText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to welcome.
        /// </summary>
        public static string SetupPageTitle {
            get {
                return ResourceManager.GetString("SetupPageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The date you selected is in the future. Is this correct?.
        /// </summary>
        public static string SetupStartDateInFutureValidation {
            get {
                return ResourceManager.GetString("SetupStartDateInFutureValidation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 6 months.
        /// </summary>
        public static string SixMonths {
            get {
                return ResourceManager.GetString("SixMonths", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Standard.
        /// </summary>
        public static string Standard {
            get {
                return ResourceManager.GetString("Standard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The date you selected is in the future. Please select another date..
        /// </summary>
        public static string StartDateInFutureValidation {
            get {
                return ResourceManager.GetString("StartDateInFutureValidation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Week starts with.
        /// </summary>
        public static string StartingWeekDaySettingText {
            get {
                return ResourceManager.GetString("StartingWeekDaySettingText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Startup page.
        /// </summary>
        public static string StartupPageSetting {
            get {
                return ResourceManager.GetString("StartupPageSetting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Statistics.
        /// </summary>
        public static string StatisticsHeader {
            get {
                return ResourceManager.GetString("StatisticsHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 3 months.
        /// </summary>
        public static string ThreeMonths {
            get {
                return ResourceManager.GetString("ThreeMonths", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Anually.
        /// </summary>
        public static string Yearly {
            get {
                return ResourceManager.GetString("Yearly", resourceCulture);
            }
        }
    }
}
